"""New Database

Revision ID: 3414dfefec1e
Revises: cbbee0e5f984
Create Date: 2021-04-01 16:49:48.658710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3414dfefec1e'
down_revision = 'cbbee0e5f984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('w_content', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'w_content')
    # ### end Alembic commands ###
