"""new

Revision ID: 3a3ddf5d7c86
Revises: cddbe11b89ae
Create Date: 2021-04-02 11:38:13.481165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3ddf5d7c86'
down_revision = 'cddbe11b89ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'c_title_2')
    op.drop_column('client', 'c_content')
    op.drop_column('client', 'c_author')
    op.drop_column('client', 'c_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('c_title', sa.VARCHAR(length=255), nullable=True))
    op.add_column('client', sa.Column('c_author', sa.VARCHAR(length=255), nullable=True))
    op.add_column('client', sa.Column('c_content', sa.VARCHAR(length=255), nullable=True))
    op.add_column('client', sa.Column('c_title_2', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
