"""New Database 2

Revision ID: cddbe11b89ae
Revises: d73e117bb391
Create Date: 2021-04-02 11:10:41.573568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddbe11b89ae'
down_revision = 'd73e117bb391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('c_img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'c_img')
    # ### end Alembic commands ###
