"""New

Revision ID: d73e117bb391
Revises: 3414dfefec1e
Create Date: 2021-04-02 11:09:03.034204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73e117bb391'
down_revision = '3414dfefec1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_title', sa.String(length=255), nullable=True),
    sa.Column('c_title_2', sa.String(length=255), nullable=True),
    sa.Column('c_author', sa.String(length=255), nullable=True),
    sa.Column('c_content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
